version: "3.8"

services:
  db:
    image: postgres
    restart: "always"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PW}
  redis:
    image: bitnami/redis
    restart: "unless-stopped"
    ports:
      - 6379:6379
    environment:
      REDIS_PASSWORD: ${REDIS_PW}
