FROM node:alpine

RUN mkdir -p /usr/src/app/server

WORKDIR /usr/src/app/server

COPY package.json yarn.lock /usr/src/app/server/

RUN apk add --no-cache python3 make g++
RUN yarn install


EXPOSE 4000
CMD [ "yarn", "dev" ]