export enum ComponentType {
  Jaahdytys = 1,
  Lammitys = 2,
  Sahkonkulutus = 3,
  Jate = 4,
  AsiakkaidenKuljetukset = 5,
  Tyomatkat = 6,
  Tyossakayntimatkat = 7,
  Tavarakuljetukset = 8,
  Elintarvikehankinnat = 9,
  YleisetHankinnat = 10,
  MuutHankinnat = 11,
  PalveluHankinnat = 12,
  KiinteistoPolttoaineet = 13,
}
