interface Municipality {
  id: number;
  name: string;
  city: string;
  stateCode: number;
  state: string;
}

const municipalitiesUnsorted: Municipality[] = [
  {
    id: 18,
    name: "Askola",
    city: "018 Askola",
    stateCode: 1,
    state: "Uusimaa",
  },
  {
    id: 49,
    name: "Espoo",
    city: "049 Espoo",
    stateCode: 1,
    state: "Uusimaa",
  },
  {
    id: 78,
    name: "Hanko",
    city: "078 Hanko",
    stateCode: 1,
    state: "Uusimaa",
  },
  {
    id: 91,
    name: "Helsinki",
    city: "091 Helsinki",
    stateCode: 1,
    state: "Uusimaa",
  },
  {
    id: 92,
    name: "Vantaa",
    city: "092 Vantaa",
    stateCode: 1,
    state: "Uusimaa",
  },
  {
    id: 106,
    name: "Hyvinkää",
    city: "106 Hyvinkää",
    stateCode: 1,
    state: "Uusimaa",
  },
  {
    id: 149,
    name: "Ingå",
    city: "149 Ingå",
    stateCode: 1,
    state: "Uusimaa",
  },
  {
    id: 186,
    name: "Järvenpää",
    city: "186 Järvenpää",
    stateCode: 1,
    state: "Uusimaa",
  },
  {
    id: 224,
    name: "Karkkila",
    city: "224 Karkkila",
    stateCode: 1,
    state: "Uusimaa",
  },
  {
    id: 235,
    name: "Kauniainen",
    city: "235 Kauniainen",
    stateCode: 1,
    state: "Uusimaa",
  },
  {
    id: 245,
    name: "Kerava",
    city: "245 Kerava",
    stateCode: 1,
    state: "Uusimaa",
  },
  {
    id: 257,
    name: "Kirkkonummi",
    city: "257 Kirkkonummi",
    stateCode: 1,
    state: "Uusimaa",
  },
  {
    id: 407,
    name: "Lapinjärvi",
    city: "407 Lapinjärvi",
    stateCode: 1,
    state: "Uusimaa",
  },
  {
    id: 434,
    name: "Loviisa",
    city: "434 Loviisa",
    stateCode: 1,
    state: "Uusimaa",
  },
  {
    id: 444,
    name: "Lohja",
    city: "444 Lohja",
    stateCode: 1,
    state: "Uusimaa",
  },
  {
    id: 504,
    name: "Myrskylä",
    city: "504 Myrskylä",
    stateCode: 1,
    state: "Uusimaa",
  },
  {
    id: 505,
    name: "Mäntsälä",
    city: "505 Mäntsälä",
    stateCode: 1,
    state: "Uusimaa",
  },
  {
    id: 543,
    name: "Nurmijärvi",
    city: "543 Nurmijärvi",
    stateCode: 1,
    state: "Uusimaa",
  },
  {
    id: 611,
    name: "Pornainen",
    city: "611 Pornainen",
    stateCode: 1,
    state: "Uusimaa",
  },
  {
    id: 616,
    name: "Pukkila",
    city: "616 Pukkila",
    stateCode: 1,
    state: "Uusimaa",
  },
  {
    id: 638,
    name: "Porvoo",
    city: "638 Porvoo",
    stateCode: 1,
    state: "Uusimaa",
  },
  {
    id: 710,
    name: "Raasepori",
    city: "710 Raasepori",
    stateCode: 1,
    state: "Uusimaa",
  },
  {
    id: 753,
    name: "Sipoo",
    city: "753 Sipoo",
    stateCode: 1,
    state: "Uusimaa",
  },
  {
    id: 755,
    name: "Siuntio",
    city: "755 Siuntio",
    stateCode: 1,
    state: "Uusimaa",
  },
  {
    id: 858,
    name: "Tuusula",
    city: "858 Tuusula",
    stateCode: 1,
    state: "Uusimaa",
  },
  {
    id: 927,
    name: "Vihti",
    city: "927 Vihti",
    stateCode: 1,
    state: "Uusimaa",
  },
  {
    id: 19,
    name: "Aura",
    city: "019 Aura",
    stateCode: 2,
    state: "Southwest Finland",
  },
  {
    id: 202,
    name: "Kaarina",
    city: "202 Kaarina",
    stateCode: 2,
    state: "Southwest Finland",
  },
  {
    id: 284,
    name: "Koski Tl",
    city: "284 Koski Tl",
    stateCode: 2,
    state: "Southwest Finland",
  },
  {
    id: 304,
    name: "Kustavi",
    city: "304 Kustavi",
    stateCode: 2,
    state: "Southwest Finland",
  },
  {
    id: 322,
    name: "Kimitoön",
    city: "322 Kimitoön",
    stateCode: 2,
    state: "Southwest Finland",
  },
  {
    id: 400,
    name: "Laitila",
    city: "400 Laitila",
    stateCode: 2,
    state: "Southwest Finland",
  },
  {
    id: 423,
    name: "Lieto",
    city: "423 Lieto",
    stateCode: 2,
    state: "Southwest Finland",
  },
  {
    id: 430,
    name: "Loimaa",
    city: "430 Loimaa",
    stateCode: 2,
    state: "Southwest Finland",
  },
  {
    id: 445,
    name: "Pargas",
    city: "445 Pargas",
    stateCode: 2,
    state: "Southwest Finland",
  },
  {
    id: 480,
    name: "Marttila",
    city: "480 Marttila",
    stateCode: 2,
    state: "Southwest Finland",
  },
  {
    id: 481,
    name: "Masku",
    city: "481 Masku",
    stateCode: 2,
    state: "Southwest Finland",
  },
  {
    id: 503,
    name: "Mynämäki",
    city: "503 Mynämäki",
    stateCode: 2,
    state: "Southwest Finland",
  },
  {
    id: 529,
    name: "Naantali",
    city: "529 Naantali",
    stateCode: 2,
    state: "Southwest Finland",
  },
  {
    id: 538,
    name: "Nousiainen",
    city: "538 Nousiainen",
    stateCode: 2,
    state: "Southwest Finland",
  },
  {
    id: 561,
    name: "Oripää",
    city: "561 Oripää",
    stateCode: 2,
    state: "Southwest Finland",
  },
  {
    id: 577,
    name: "Paimio",
    city: "577 Paimio",
    stateCode: 2,
    state: "Southwest Finland",
  },
  {
    id: 631,
    name: "Pyhäranta",
    city: "631 Pyhäranta",
    stateCode: 2,
    state: "Southwest Finland",
  },
  {
    id: 636,
    name: "Pöytyä",
    city: "636 Pöytyä",
    stateCode: 2,
    state: "Southwest Finland",
  },
  {
    id: 680,
    name: "Raisio",
    city: "680 Raisio",
    stateCode: 2,
    state: "Southwest Finland",
  },
  {
    id: 704,
    name: "Rusko",
    city: "704 Rusko",
    stateCode: 2,
    state: "Southwest Finland",
  },
  {
    id: 734,
    name: "Salo",
    city: "734 Salo",
    stateCode: 2,
    state: "Southwest Finland",
  },
  {
    id: 738,
    name: "Sauvo",
    city: "738 Sauvo",
    stateCode: 2,
    state: "Southwest Finland",
  },
  {
    id: 761,
    name: "Somero",
    city: "761 Somero",
    stateCode: 2,
    state: "Southwest Finland",
  },
  {
    id: 833,
    name: "Taivassalo",
    city: "833 Taivassalo",
    stateCode: 2,
    state: "Southwest Finland",
  },
  {
    id: 853,
    name: "Turku",
    city: "853 Turku",
    stateCode: 2,
    state: "Southwest Finland",
  },
  {
    id: 895,
    name: "Uusikaupunki",
    city: "895 Uusikaupunki",
    stateCode: 2,
    state: "Southwest Finland",
  },
  {
    id: 918,
    name: "Vehmaa",
    city: "918 Vehmaa",
    stateCode: 2,
    state: "Southwest Finland",
  },
  {
    id: 50,
    name: "Eura",
    city: "050 Eura",
    stateCode: 4,
    state: "Satakunta",
  },
  {
    id: 51,
    name: "Eurajoki",
    city: "051 Eurajoki",
    stateCode: 4,
    state: "Satakunta",
  },
  {
    id: 79,
    name: "Harjavalta",
    city: "079 Harjavalta",
    stateCode: 4,
    state: "Satakunta",
  },
  {
    id: 99,
    name: "Honkajoki",
    city: "099 Honkajoki",
    stateCode: 4,
    state: "Satakunta",
  },
  {
    id: 102,
    name: "Huittinen",
    city: "102 Huittinen",
    stateCode: 4,
    state: "Satakunta",
  },
  {
    id: 181,
    name: "Jämijärvi",
    city: "181 Jämijärvi",
    stateCode: 4,
    state: "Satakunta",
  },
  {
    id: 214,
    name: "Kankaanpää",
    city: "214 Kankaanpää",
    stateCode: 4,
    state: "Satakunta",
  },
  {
    id: 230,
    name: "Karvia",
    city: "230 Karvia",
    stateCode: 4,
    state: "Satakunta",
  },
  {
    id: 271,
    name: "Kokemäki",
    city: "271 Kokemäki",
    stateCode: 4,
    state: "Satakunta",
  },
  {
    id: 484,
    name: "Merikarvia",
    city: "484 Merikarvia",
    stateCode: 4,
    state: "Satakunta",
  },
  {
    id: 531,
    name: "Nakkila",
    city: "531 Nakkila",
    stateCode: 4,
    state: "Satakunta",
  },
  {
    id: 608,
    name: "Pomarkku",
    city: "608 Pomarkku",
    stateCode: 4,
    state: "Satakunta",
  },
  {
    id: 609,
    name: "Pori",
    city: "609 Pori",
    stateCode: 4,
    state: "Satakunta",
  },
  {
    id: 684,
    name: "Rauma",
    city: "684 Rauma",
    stateCode: 4,
    state: "Satakunta",
  },
  {
    id: 747,
    name: "Siikainen",
    city: "747 Siikainen",
    stateCode: 4,
    state: "Satakunta",
  },
  {
    id: 783,
    name: "Säkylä",
    city: "783 Säkylä",
    stateCode: 4,
    state: "Satakunta",
  },
  {
    id: 886,
    name: "Ulvila",
    city: "886 Ulvila",
    stateCode: 4,
    state: "Satakunta",
  },
  {
    id: 61,
    name: "Forssa",
    city: "061 Forssa",
    stateCode: 5,
    state: "Kanta-Häme",
  },
  {
    id: 82,
    name: "Hattula",
    city: "082 Hattula",
    stateCode: 5,
    state: "Kanta-Häme",
  },
  {
    id: 86,
    name: "Hausjärvi",
    city: "086 Hausjärvi",
    stateCode: 5,
    state: "Kanta-Häme",
  },
  {
    id: 103,
    name: "Humppila",
    city: "103 Humppila",
    stateCode: 5,
    state: "Kanta-Häme",
  },
  {
    id: 109,
    name: "Hämeenlinna",
    city: "109 Hämeenlinna",
    stateCode: 5,
    state: "Kanta-Häme",
  },
  {
    id: 165,
    name: "Janakkala",
    city: "165 Janakkala",
    stateCode: 5,
    state: "Kanta-Häme",
  },
  {
    id: 169,
    name: "Jokioinen",
    city: "169 Jokioinen",
    stateCode: 5,
    state: "Kanta-Häme",
  },
  {
    id: 433,
    name: "Loppi",
    city: "433 Loppi",
    stateCode: 5,
    state: "Kanta-Häme",
  },
  {
    id: 694,
    name: "Riihimäki",
    city: "694 Riihimäki",
    stateCode: 5,
    state: "Kanta-Häme",
  },
  {
    id: 834,
    name: "Tammela",
    city: "834 Tammela",
    stateCode: 5,
    state: "Kanta-Häme",
  },
  {
    id: 981,
    name: "Ypäjä",
    city: "981 Ypäjä",
    stateCode: 5,
    state: "Kanta-Häme",
  },
  {
    id: 20,
    name: "Akaa",
    city: "020 Akaa",
    stateCode: 6,
    state: "Pirkanmaa",
  },
  {
    id: 108,
    name: "Hämeenkyrö",
    city: "108 Hämeenkyrö",
    stateCode: 6,
    state: "Pirkanmaa",
  },
  {
    id: 143,
    name: "Ikaalinen",
    city: "143 Ikaalinen",
    stateCode: 6,
    state: "Pirkanmaa",
  },
  {
    id: 177,
    name: "Juupajoki",
    city: "177 Juupajoki",
    stateCode: 6,
    state: "Pirkanmaa",
  },
  {
    id: 211,
    name: "Kangasala",
    city: "211 Kangasala",
    stateCode: 6,
    state: "Pirkanmaa",
  },
  {
    id: 250,
    name: "Kihniö",
    city: "250 Kihniö",
    stateCode: 6,
    state: "Pirkanmaa",
  },
  {
    id: 418,
    name: "Lempäälä",
    city: "418 Lempäälä",
    stateCode: 6,
    state: "Pirkanmaa",
  },
  {
    id: 508,
    name: "Mänttä-Vilppula",
    city: "508 Mänttä-Vilppula",
    stateCode: 6,
    state: "Pirkanmaa",
  },
  {
    id: 536,
    name: "Nokia",
    city: "536 Nokia",
    stateCode: 6,
    state: "Pirkanmaa",
  },
  {
    id: 562,
    name: "Orivesi",
    city: "562 Orivesi",
    stateCode: 6,
    state: "Pirkanmaa",
  },
  {
    id: 581,
    name: "Parkano",
    city: "581 Parkano",
    stateCode: 6,
    state: "Pirkanmaa",
  },
  {
    id: 604,
    name: "Pirkkala",
    city: "604 Pirkkala",
    stateCode: 6,
    state: "Pirkanmaa",
  },
  {
    id: 619,
    name: "Punkalaidun",
    city: "619 Punkalaidun",
    stateCode: 6,
    state: "Pirkanmaa",
  },
  {
    id: 635,
    name: "Pälkäne",
    city: "635 Pälkäne",
    stateCode: 6,
    state: "Pirkanmaa",
  },
  {
    id: 702,
    name: "Ruovesi",
    city: "702 Ruovesi",
    stateCode: 6,
    state: "Pirkanmaa",
  },
  {
    id: 790,
    name: "Sastamala",
    city: "790 Sastamala",
    stateCode: 6,
    state: "Pirkanmaa",
  },
  {
    id: 837,
    name: "Tampere",
    city: "837 Tampere",
    stateCode: 6,
    state: "Pirkanmaa",
  },
  {
    id: 887,
    name: "Urjala",
    city: "887 Urjala",
    stateCode: 6,
    state: "Pirkanmaa",
  },
  {
    id: 908,
    name: "Valkeakoski",
    city: "908 Valkeakoski",
    stateCode: 6,
    state: "Pirkanmaa",
  },
  {
    id: 922,
    name: "Vesilahti",
    city: "922 Vesilahti",
    stateCode: 6,
    state: "Pirkanmaa",
  },
  {
    id: 936,
    name: "Virrat",
    city: "936 Virrat",
    stateCode: 6,
    state: "Pirkanmaa",
  },
  {
    id: 980,
    name: "Ylöjärvi",
    city: "980 Ylöjärvi",
    stateCode: 6,
    state: "Pirkanmaa",
  },
  {
    id: 16,
    name: "Asikkala",
    city: "016 Asikkala",
    stateCode: 7,
    state: "Päijät-Häme",
  },
  {
    id: 81,
    name: "Hartola",
    city: "081 Hartola",
    stateCode: 7,
    state: "Päijät-Häme",
  },
  {
    id: 98,
    name: "Hollola",
    city: "098 Hollola",
    stateCode: 7,
    state: "Päijät-Häme",
  },
  {
    id: 111,
    name: "Heinola",
    city: "111 Heinola",
    stateCode: 7,
    state: "Päijät-Häme",
  },
  {
    id: 316,
    name: "Kärkölä",
    city: "316 Kärkölä",
    stateCode: 7,
    state: "Päijät-Häme",
  },
  {
    id: 398,
    name: "Lahti",
    city: "398 Lahti",
    stateCode: 7,
    state: "Päijät-Häme",
  },
  {
    id: 560,
    name: "Orimattila",
    city: "560 Orimattila",
    stateCode: 7,
    state: "Päijät-Häme",
  },
  {
    id: 576,
    name: "Padasjoki",
    city: "576 Padasjoki",
    stateCode: 7,
    state: "Päijät-Häme",
  },
  {
    id: 781,
    name: "Sysmä",
    city: "781 Sysmä",
    stateCode: 7,
    state: "Päijät-Häme",
  },
  {
    id: 75,
    name: "Hamina",
    city: "075 Hamina",
    stateCode: 8,
    state: "Kymenlaakso",
  },
  {
    id: 142,
    name: "Iitti",
    city: "142 Iitti",
    stateCode: 8,
    state: "Kymenlaakso",
  },
  {
    id: 285,
    name: "Kotka",
    city: "285 Kotka",
    stateCode: 8,
    state: "Kymenlaakso",
  },
  {
    id: 286,
    name: "Kouvola",
    city: "286 Kouvola",
    stateCode: 8,
    state: "Kymenlaakso",
  },
  {
    id: 489,
    name: "Miehikkälä",
    city: "489 Miehikkälä",
    stateCode: 8,
    state: "Kymenlaakso",
  },
  {
    id: 624,
    name: "Pyhtää",
    city: "624 Pyhtää",
    stateCode: 8,
    state: "Kymenlaakso",
  },
  {
    id: 935,
    name: "Virolahti",
    city: "935 Virolahti",
    stateCode: 8,
    state: "Kymenlaakso",
  },
  {
    id: 153,
    name: "Imatra",
    city: "153 Imatra",
    stateCode: 9,
    state: "South Karelia",
  },
  {
    id: 405,
    name: "Lappeenranta",
    city: "405 Lappeenranta",
    stateCode: 9,
    state: "South Karelia",
  },
  {
    id: 416,
    name: "Lemi",
    city: "416 Lemi",
    stateCode: 9,
    state: "South Karelia",
  },
  {
    id: 441,
    name: "Luumäki",
    city: "441 Luumäki",
    stateCode: 9,
    state: "South Karelia",
  },
  {
    id: 580,
    name: "Parikkala",
    city: "580 Parikkala",
    stateCode: 9,
    state: "South Karelia",
  },
  {
    id: 689,
    name: "Rautjärvi",
    city: "689 Rautjärvi",
    stateCode: 9,
    state: "South Karelia",
  },
  {
    id: 700,
    name: "Ruokolahti",
    city: "700 Ruokolahti",
    stateCode: 9,
    state: "South Karelia",
  },
  {
    id: 739,
    name: "Savitaipale",
    city: "739 Savitaipale",
    stateCode: 9,
    state: "South Karelia",
  },
  {
    id: 831,
    name: "Taipalsaari",
    city: "831 Taipalsaari",
    stateCode: 9,
    state: "South Karelia",
  },
  {
    id: 46,
    name: "Enonkoski",
    city: "046 Enonkoski",
    stateCode: 10,
    state: "South Savo",
  },
  {
    id: 90,
    name: "Heinävesi",
    city: "090 Heinävesi",
    stateCode: 10,
    state: "South Savo",
  },
  {
    id: 97,
    name: "Hirvensalmi",
    city: "097 Hirvensalmi",
    stateCode: 10,
    state: "South Savo",
  },
  {
    id: 171,
    name: "Joroinen",
    city: "171 Joroinen",
    stateCode: 10,
    state: "South Savo",
  },
  {
    id: 178,
    name: "Juva",
    city: "178 Juva",
    stateCode: 10,
    state: "South Savo",
  },
  {
    id: 213,
    name: "Kangasniemi",
    city: "213 Kangasniemi",
    stateCode: 10,
    state: "South Savo",
  },
  {
    id: 491,
    name: "Mikkeli",
    city: "491 Mikkeli",
    stateCode: 10,
    state: "South Savo",
  },
  {
    id: 507,
    name: "Mäntyharju",
    city: "507 Mäntyharju",
    stateCode: 10,
    state: "South Savo",
  },
  {
    id: 588,
    name: "Pertunmaa",
    city: "588 Pertunmaa",
    stateCode: 10,
    state: "South Savo",
  },
  {
    id: 593,
    name: "Pieksämäki",
    city: "593 Pieksämäki",
    stateCode: 10,
    state: "South Savo",
  },
  {
    id: 623,
    name: "Puumala",
    city: "623 Puumala",
    stateCode: 10,
    state: "South Savo",
  },
  {
    id: 681,
    name: "Rantasalmi",
    city: "681 Rantasalmi",
    stateCode: 10,
    state: "South Savo",
  },
  {
    id: 740,
    name: "Savonlinna",
    city: "740 Savonlinna",
    stateCode: 10,
    state: "South Savo",
  },
  {
    id: 768,
    name: "Sulkava",
    city: "768 Sulkava",
    stateCode: 10,
    state: "South Savo",
  },
  {
    id: 140,
    name: "Iisalmi",
    city: "140 Iisalmi",
    stateCode: 11,
    state: "North Savo",
  },
  {
    id: 204,
    name: "Kaavi",
    city: "204 Kaavi",
    stateCode: 11,
    state: "North Savo",
  },
  {
    id: 239,
    name: "Keitele",
    city: "239 Keitele",
    stateCode: 11,
    state: "North Savo",
  },
  {
    id: 263,
    name: "Kiuruvesi",
    city: "263 Kiuruvesi",
    stateCode: 11,
    state: "North Savo",
  },
  {
    id: 297,
    name: "Kuopio",
    city: "297 Kuopio",
    stateCode: 11,
    state: "North Savo",
  },
  {
    id: 402,
    name: "Lapinlahti",
    city: "402 Lapinlahti",
    stateCode: 11,
    state: "North Savo",
  },
  {
    id: 420,
    name: "Leppävirta",
    city: "420 Leppävirta",
    stateCode: 11,
    state: "North Savo",
  },
  {
    id: 595,
    name: "Pielavesi",
    city: "595 Pielavesi",
    stateCode: 11,
    state: "North Savo",
  },
  {
    id: 686,
    name: "Rautalampi",
    city: "686 Rautalampi",
    stateCode: 11,
    state: "North Savo",
  },
  {
    id: 687,
    name: "Rautavaara",
    city: "687 Rautavaara",
    stateCode: 11,
    state: "North Savo",
  },
  {
    id: 749,
    name: "Siilinjärvi",
    city: "749 Siilinjärvi",
    stateCode: 11,
    state: "North Savo",
  },
  {
    id: 762,
    name: "Sonkajärvi",
    city: "762 Sonkajärvi",
    stateCode: 11,
    state: "North Savo",
  },
  {
    id: 778,
    name: "Suonenjoki",
    city: "778 Suonenjoki",
    stateCode: 11,
    state: "North Savo",
  },
  {
    id: 844,
    name: "Tervo",
    city: "844 Tervo",
    stateCode: 11,
    state: "North Savo",
  },
  {
    id: 857,
    name: "Tuusniemi",
    city: "857 Tuusniemi",
    stateCode: 11,
    state: "North Savo",
  },
  {
    id: 915,
    name: "Varkaus",
    city: "915 Varkaus",
    stateCode: 11,
    state: "North Savo",
  },
  {
    id: 921,
    name: "Vesanto",
    city: "921 Vesanto",
    stateCode: 11,
    state: "North Savo",
  },
  {
    id: 925,
    name: "Vieremä",
    city: "925 Vieremä",
    stateCode: 11,
    state: "North Savo",
  },
  {
    id: 146,
    name: "Ilomantsi",
    city: "146 Ilomantsi",
    stateCode: 12,
    state: "North Karelia",
  },
  {
    id: 167,
    name: "Joensuu",
    city: "167 Joensuu",
    stateCode: 12,
    state: "North Karelia",
  },
  {
    id: 176,
    name: "Juuka",
    city: "176 Juuka",
    stateCode: 12,
    state: "North Karelia",
  },
  {
    id: 260,
    name: "Kitee",
    city: "260 Kitee",
    stateCode: 12,
    state: "North Karelia",
  },
  {
    id: 276,
    name: "Kontiolahti",
    city: "276 Kontiolahti",
    stateCode: 12,
    state: "North Karelia",
  },
  {
    id: 309,
    name: "Outokumpu",
    city: "309 Outokumpu",
    stateCode: 12,
    state: "North Karelia",
  },
  {
    id: 422,
    name: "Lieksa",
    city: "422 Lieksa",
    stateCode: 12,
    state: "North Karelia",
  },
  {
    id: 426,
    name: "Liperi",
    city: "426 Liperi",
    stateCode: 12,
    state: "North Karelia",
  },
  {
    id: 541,
    name: "Nurmes",
    city: "541 Nurmes",
    stateCode: 12,
    state: "North Karelia",
  },
  {
    id: 607,
    name: "Polvijärvi",
    city: "607 Polvijärvi",
    stateCode: 12,
    state: "North Karelia",
  },
  {
    id: 707,
    name: "Rääkkylä",
    city: "707 Rääkkylä",
    stateCode: 12,
    state: "North Karelia",
  },
  {
    id: 848,
    name: "Tohmajärvi",
    city: "848 Tohmajärvi",
    stateCode: 12,
    state: "North Karelia",
  },
  {
    id: 77,
    name: "Hankasalmi",
    city: "077 Hankasalmi",
    stateCode: 13,
    state: "Central Finland",
  },
  {
    id: 172,
    name: "Joutsa",
    city: "172 Joutsa",
    stateCode: 13,
    state: "Central Finland",
  },
  {
    id: 179,
    name: "Jyväskylä",
    city: "179 Jyväskylä",
    stateCode: 13,
    state: "Central Finland",
  },
  {
    id: 182,
    name: "Jämsä",
    city: "182 Jämsä",
    stateCode: 13,
    state: "Central Finland",
  },
  {
    id: 216,
    name: "Kannonkoski",
    city: "216 Kannonkoski",
    stateCode: 13,
    state: "Central Finland",
  },
  {
    id: 226,
    name: "Karstula",
    city: "226 Karstula",
    stateCode: 13,
    state: "Central Finland",
  },
  {
    id: 249,
    name: "Keuruu",
    city: "249 Keuruu",
    stateCode: 13,
    state: "Central Finland",
  },
  {
    id: 256,
    name: "Kinnula",
    city: "256 Kinnula",
    stateCode: 13,
    state: "Central Finland",
  },
  {
    id: 265,
    name: "Kivijärvi",
    city: "265 Kivijärvi",
    stateCode: 13,
    state: "Central Finland",
  },
  {
    id: 275,
    name: "Konnevesi",
    city: "275 Konnevesi",
    stateCode: 13,
    state: "Central Finland",
  },
  {
    id: 291,
    name: "Kuhmoinen",
    city: "291 Kuhmoinen",
    stateCode: 13,
    state: "Central Finland",
  },
  {
    id: 312,
    name: "Kyyjärvi",
    city: "312 Kyyjärvi",
    stateCode: 13,
    state: "Central Finland",
  },
  {
    id: 410,
    name: "Laukaa",
    city: "410 Laukaa",
    stateCode: 13,
    state: "Central Finland",
  },
  {
    id: 435,
    name: "Luhanka",
    city: "435 Luhanka",
    stateCode: 13,
    state: "Central Finland",
  },
  {
    id: 495,
    name: "Multia",
    city: "495 Multia",
    stateCode: 13,
    state: "Central Finland",
  },
  {
    id: 500,
    name: "Muurame",
    city: "500 Muurame",
    stateCode: 13,
    state: "Central Finland",
  },
  {
    id: 592,
    name: "Petäjävesi",
    city: "592 Petäjävesi",
    stateCode: 13,
    state: "Central Finland",
  },
  {
    id: 601,
    name: "Pihtipudas",
    city: "601 Pihtipudas",
    stateCode: 13,
    state: "Central Finland",
  },
  {
    id: 729,
    name: "Saarijärvi",
    city: "729 Saarijärvi",
    stateCode: 13,
    state: "Central Finland",
  },
  {
    id: 850,
    name: "Toivakka",
    city: "850 Toivakka",
    stateCode: 13,
    state: "Central Finland",
  },
  {
    id: 892,
    name: "Uurainen",
    city: "892 Uurainen",
    stateCode: 13,
    state: "Central Finland",
  },
  {
    id: 931,
    name: "Viitasaari",
    city: "931 Viitasaari",
    stateCode: 13,
    state: "Central Finland",
  },
  {
    id: 992,
    name: "Äänekoski",
    city: "992 Äänekoski",
    stateCode: 13,
    state: "Central Finland",
  },
  {
    id: 5,
    name: "Alajärvi",
    city: "005 Alajärvi",
    stateCode: 14,
    state: "South Ostrobothnia",
  },
  {
    id: 10,
    name: "Alavus",
    city: "010 Alavus",
    stateCode: 14,
    state: "South Ostrobothnia",
  },
  {
    id: 52,
    name: "Evijärvi",
    city: "052 Evijärvi",
    stateCode: 14,
    state: "South Ostrobothnia",
  },
  {
    id: 145,
    name: "Ilmajoki",
    city: "145 Ilmajoki",
    stateCode: 14,
    state: "South Ostrobothnia",
  },
  {
    id: 151,
    name: "Isojoki",
    city: "151 Isojoki",
    stateCode: 14,
    state: "South Ostrobothnia",
  },
  {
    id: 218,
    name: "Karijoki",
    city: "218 Karijoki",
    stateCode: 14,
    state: "South Ostrobothnia",
  },
  {
    id: 232,
    name: "Kauhajoki",
    city: "232 Kauhajoki",
    stateCode: 14,
    state: "South Ostrobothnia",
  },
  {
    id: 233,
    name: "Kauhava",
    city: "233 Kauhava",
    stateCode: 14,
    state: "South Ostrobothnia",
  },
  {
    id: 300,
    name: "Kuortane",
    city: "300 Kuortane",
    stateCode: 14,
    state: "South Ostrobothnia",
  },
  {
    id: 301,
    name: "Kurikka",
    city: "301 Kurikka",
    stateCode: 14,
    state: "South Ostrobothnia",
  },
  {
    id: 403,
    name: "Lappajärvi",
    city: "403 Lappajärvi",
    stateCode: 14,
    state: "South Ostrobothnia",
  },
  {
    id: 408,
    name: "Lapua",
    city: "408 Lapua",
    stateCode: 14,
    state: "South Ostrobothnia",
  },
  {
    id: 743,
    name: "Seinäjoki",
    city: "743 Seinäjoki",
    stateCode: 14,
    state: "South Ostrobothnia",
  },
  {
    id: 759,
    name: "Soini",
    city: "759 Soini",
    stateCode: 14,
    state: "South Ostrobothnia",
  },
  {
    id: 846,
    name: "Teuva",
    city: "846 Teuva",
    stateCode: 14,
    state: "South Ostrobothnia",
  },
  {
    id: 934,
    name: "Vimpeli",
    city: "934 Vimpeli",
    stateCode: 14,
    state: "South Ostrobothnia",
  },
  {
    id: 989,
    name: "Ähtäri",
    city: "989 Ähtäri",
    stateCode: 14,
    state: "South Ostrobothnia",
  },
  {
    id: 152,
    name: "Isokyrö",
    city: "152 Isokyrö",
    stateCode: 15,
    state: "Ostrobothnia",
  },
  {
    id: 231,
    name: "Kaskinen",
    city: "231 Kaskinen",
    stateCode: 15,
    state: "Ostrobothnia",
  },
  {
    id: 280,
    name: "Korsnäs",
    city: "280 Korsnäs",
    stateCode: 15,
    state: "Ostrobothnia",
  },
  {
    id: 287,
    name: "Kristinestad",
    city: "287 Kristinestad",
    stateCode: 15,
    state: "Ostrobothnia",
  },
  {
    id: 288,
    name: "Kronoby",
    city: "288 Kronoby",
    stateCode: 15,
    state: "Ostrobothnia",
  },
  {
    id: 399,
    name: "Laihia",
    city: "399 Laihia",
    stateCode: 15,
    state: "Ostrobothnia",
  },
  {
    id: 440,
    name: "Larsmo",
    city: "440 Larsmo",
    stateCode: 15,
    state: "Ostrobothnia",
  },
  {
    id: 475,
    name: "Malax",
    city: "475 Malax",
    stateCode: 15,
    state: "Ostrobothnia",
  },
  {
    id: 499,
    name: "Korsholm",
    city: "499 Korsholm",
    stateCode: 15,
    state: "Ostrobothnia",
  },
  {
    id: 545,
    name: "Närpes",
    city: "545 Närpes",
    stateCode: 15,
    state: "Ostrobothnia",
  },
  {
    id: 598,
    name: "Jakobstad",
    city: "598 Jakobstad",
    stateCode: 15,
    state: "Ostrobothnia",
  },
  {
    id: 599,
    name: "Pedersöre",
    city: "599 Pedersöre",
    stateCode: 15,
    state: "Ostrobothnia",
  },
  {
    id: 893,
    name: "Nykarleby",
    city: "893 Nykarleby",
    stateCode: 15,
    state: "Ostrobothnia",
  },
  {
    id: 905,
    name: "Vaasa",
    city: "905 Vaasa",
    stateCode: 15,
    state: "Ostrobothnia",
  },
  {
    id: 946,
    name: "Vöyri",
    city: "946 Vöyri",
    stateCode: 15,
    state: "Ostrobothnia",
  },
  {
    id: 74,
    name: "Halsua",
    city: "074 Halsua",
    stateCode: 16,
    state: "Central Ostrobothnia",
  },
  {
    id: 217,
    name: "Kannus",
    city: "217 Kannus",
    stateCode: 16,
    state: "Central Ostrobothnia",
  },
  {
    id: 236,
    name: "Kaustinen",
    city: "236 Kaustinen",
    stateCode: 16,
    state: "Central Ostrobothnia",
  },
  {
    id: 272,
    name: "Kokkola",
    city: "272 Kokkola",
    stateCode: 16,
    state: "Central Ostrobothnia",
  },
  {
    id: 421,
    name: "Lestijärvi",
    city: "421 Lestijärvi",
    stateCode: 16,
    state: "Central Ostrobothnia",
  },
  {
    id: 584,
    name: "Perho",
    city: "584 Perho",
    stateCode: 16,
    state: "Central Ostrobothnia",
  },
  {
    id: 849,
    name: "Toholampi",
    city: "849 Toholampi",
    stateCode: 16,
    state: "Central Ostrobothnia",
  },
  {
    id: 924,
    name: "Veteli",
    city: "924 Veteli",
    stateCode: 16,
    state: "Central Ostrobothnia",
  },
  {
    id: 9,
    name: "Alavieska",
    city: "009 Alavieska",
    stateCode: 17,
    state: "North Ostrobothnia",
  },
  {
    id: 69,
    name: "Haapajärvi",
    city: "069 Haapajärvi",
    stateCode: 17,
    state: "North Ostrobothnia",
  },
  {
    id: 71,
    name: "Haapavesi",
    city: "071 Haapavesi",
    stateCode: 17,
    state: "North Ostrobothnia",
  },
  {
    id: 72,
    name: "Hailuoto",
    city: "072 Hailuoto",
    stateCode: 17,
    state: "North Ostrobothnia",
  },
  {
    id: 139,
    name: "Ii",
    city: "139 Ii",
    stateCode: 17,
    state: "North Ostrobothnia",
  },
  {
    id: 208,
    name: "Kalajoki",
    city: "208 Kalajoki",
    stateCode: 17,
    state: "North Ostrobothnia",
  },
  {
    id: 244,
    name: "Kempele",
    city: "244 Kempele",
    stateCode: 17,
    state: "North Ostrobothnia",
  },
  {
    id: 305,
    name: "Kuusamo",
    city: "305 Kuusamo",
    stateCode: 17,
    state: "North Ostrobothnia",
  },
  {
    id: 317,
    name: "Kärsämäki",
    city: "317 Kärsämäki",
    stateCode: 17,
    state: "North Ostrobothnia",
  },
  {
    id: 425,
    name: "Liminka",
    city: "425 Liminka",
    stateCode: 17,
    state: "North Ostrobothnia",
  },
  {
    id: 436,
    name: "Lumijoki",
    city: "436 Lumijoki",
    stateCode: 17,
    state: "North Ostrobothnia",
  },
  {
    id: 483,
    name: "Merijärvi",
    city: "483 Merijärvi",
    stateCode: 17,
    state: "North Ostrobothnia",
  },
  {
    id: 494,
    name: "Muhos",
    city: "494 Muhos",
    stateCode: 17,
    state: "North Ostrobothnia",
  },
  {
    id: 535,
    name: "Nivala",
    city: "535 Nivala",
    stateCode: 17,
    state: "North Ostrobothnia",
  },
  {
    id: 563,
    name: "Oulainen",
    city: "563 Oulainen",
    stateCode: 17,
    state: "North Ostrobothnia",
  },
  {
    id: 564,
    name: "Oulu",
    city: "564 Oulu",
    stateCode: 17,
    state: "North Ostrobothnia",
  },
  {
    id: 615,
    name: "Pudasjärvi",
    city: "615 Pudasjärvi",
    stateCode: 17,
    state: "North Ostrobothnia",
  },
  {
    id: 625,
    name: "Pyhäjoki",
    city: "625 Pyhäjoki",
    stateCode: 17,
    state: "North Ostrobothnia",
  },
  {
    id: 626,
    name: "Pyhäjärvi",
    city: "626 Pyhäjärvi",
    stateCode: 17,
    state: "North Ostrobothnia",
  },
  {
    id: 630,
    name: "Pyhäntä",
    city: "630 Pyhäntä",
    stateCode: 17,
    state: "North Ostrobothnia",
  },
  {
    id: 678,
    name: "Raahe",
    city: "678 Raahe",
    stateCode: 17,
    state: "North Ostrobothnia",
  },
  {
    id: 691,
    name: "Reisjärvi",
    city: "691 Reisjärvi",
    stateCode: 17,
    state: "North Ostrobothnia",
  },
  {
    id: 746,
    name: "Sievi",
    city: "746 Sievi",
    stateCode: 17,
    state: "North Ostrobothnia",
  },
  {
    id: 748,
    name: "Siikajoki",
    city: "748 Siikajoki",
    stateCode: 17,
    state: "North Ostrobothnia",
  },
  {
    id: 785,
    name: "Vaala",
    city: "785 Vaala",
    stateCode: 17,
    state: "North Ostrobothnia",
  },
  {
    id: 791,
    name: "Siikalatva",
    city: "791 Siikalatva",
    stateCode: 17,
    state: "North Ostrobothnia",
  },
  {
    id: 832,
    name: "Taivalkoski",
    city: "832 Taivalkoski",
    stateCode: 17,
    state: "North Ostrobothnia",
  },
  {
    id: 859,
    name: "Tyrnävä",
    city: "859 Tyrnävä",
    stateCode: 17,
    state: "North Ostrobothnia",
  },
  {
    id: 889,
    name: "Utajärvi",
    city: "889 Utajärvi",
    stateCode: 17,
    state: "North Ostrobothnia",
  },
  {
    id: 977,
    name: "Ylivieska",
    city: "977 Ylivieska",
    stateCode: 17,
    state: "North Ostrobothnia",
  },
  {
    id: 105,
    name: "Hyrynsalmi",
    city: "105 Hyrynsalmi",
    stateCode: 18,
    state: "Kainuu",
  },
  {
    id: 205,
    name: "Kajaani",
    city: "205 Kajaani",
    stateCode: 18,
    state: "Kainuu",
  },
  {
    id: 290,
    name: "Kuhmo",
    city: "290 Kuhmo",
    stateCode: 18,
    state: "Kainuu",
  },
  {
    id: 578,
    name: "Paltamo",
    city: "578 Paltamo",
    stateCode: 18,
    state: "Kainuu",
  },
  {
    id: 620,
    name: "Puolanka",
    city: "620 Puolanka",
    stateCode: 18,
    state: "Kainuu",
  },
  {
    id: 697,
    name: "Ristijärvi",
    city: "697 Ristijärvi",
    stateCode: 18,
    state: "Kainuu",
  },
  {
    id: 765,
    name: "Sotkamo",
    city: "765 Sotkamo",
    stateCode: 18,
    state: "Kainuu",
  },
  {
    id: 777,
    name: "Suomussalmi",
    city: "777 Suomussalmi",
    stateCode: 18,
    state: "Kainuu",
  },
  {
    id: 47,
    name: "Enontekiö",
    city: "047 Enontekiö",
    stateCode: 19,
    state: "Lapland",
  },
  {
    id: 148,
    name: "Inari",
    city: "148 Inari",
    stateCode: 19,
    state: "Lapland",
  },
  {
    id: 240,
    name: "Kemi",
    city: "240 Kemi",
    stateCode: 19,
    state: "Lapland",
  },
  {
    id: 241,
    name: "Keminmaa",
    city: "241 Keminmaa",
    stateCode: 19,
    state: "Lapland",
  },
  {
    id: 261,
    name: "Kittilä",
    city: "261 Kittilä",
    stateCode: 19,
    state: "Lapland",
  },
  {
    id: 273,
    name: "Kolari",
    city: "273 Kolari",
    stateCode: 19,
    state: "Lapland",
  },
  {
    id: 320,
    name: "Kemijärvi",
    city: "320 Kemijärvi",
    stateCode: 19,
    state: "Lapland",
  },
  {
    id: 498,
    name: "Muonio",
    city: "498 Muonio",
    stateCode: 19,
    state: "Lapland",
  },
  {
    id: 583,
    name: "Pelkosenniemi",
    city: "583 Pelkosenniemi",
    stateCode: 19,
    state: "Lapland",
  },
  {
    id: 614,
    name: "Posio",
    city: "614 Posio",
    stateCode: 19,
    state: "Lapland",
  },
  {
    id: 683,
    name: "Ranua",
    city: "683 Ranua",
    stateCode: 19,
    state: "Lapland",
  },
  {
    id: 698,
    name: "Rovaniemi",
    city: "698 Rovaniemi",
    stateCode: 19,
    state: "Lapland",
  },
  {
    id: 732,
    name: "Salla",
    city: "732 Salla",
    stateCode: 19,
    state: "Lapland",
  },
  {
    id: 742,
    name: "Savukoski",
    city: "742 Savukoski",
    stateCode: 19,
    state: "Lapland",
  },
  {
    id: 751,
    name: "Simo",
    city: "751 Simo",
    stateCode: 19,
    state: "Lapland",
  },
  {
    id: 758,
    name: "Sodankylä",
    city: "758 Sodankylä",
    stateCode: 19,
    state: "Lapland",
  },
  {
    id: 845,
    name: "Tervola",
    city: "845 Tervola",
    stateCode: 19,
    state: "Lapland",
  },
  {
    id: 851,
    name: "Tornio",
    city: "851 Tornio",
    stateCode: 19,
    state: "Lapland",
  },
  {
    id: 854,
    name: "Pello",
    city: "854 Pello",
    stateCode: 19,
    state: "Lapland",
  },
  {
    id: 890,
    name: "Utsjoki",
    city: "890 Utsjoki",
    stateCode: 19,
    state: "Lapland",
  },
  {
    id: 976,
    name: "Ylitornio",
    city: "976 Ylitornio",
    stateCode: 19,
    state: "Lapland",
  },
  {
    id: 35,
    name: "Brändö",
    city: "035 Brändö",
    stateCode: 21,
    state: "Åland",
  },
  {
    id: 43,
    name: "Eckerö",
    city: "043 Eckerö",
    stateCode: 21,
    state: "Åland",
  },
  {
    id: 60,
    name: "Finström",
    city: "060 Finström",
    stateCode: 21,
    state: "Åland",
  },
  {
    id: 62,
    name: "Föglö",
    city: "062 Föglö",
    stateCode: 21,
    state: "Åland",
  },
  {
    id: 65,
    name: "Geta",
    city: "065 Geta",
    stateCode: 21,
    state: "Åland",
  },
  {
    id: 76,
    name: "Hammarland",
    city: "076 Hammarland",
    stateCode: 21,
    state: "Åland",
  },
  {
    id: 170,
    name: "Jomala",
    city: "170 Jomala",
    stateCode: 21,
    state: "Åland",
  },
  {
    id: 295,
    name: "Kumlinge",
    city: "295 Kumlinge",
    stateCode: 21,
    state: "Åland",
  },
  {
    id: 318,
    name: "Kökar",
    city: "318 Kökar",
    stateCode: 21,
    state: "Åland",
  },
  {
    id: 417,
    name: "Lemland",
    city: "417 Lemland",
    stateCode: 21,
    state: "Åland",
  },
  {
    id: 438,
    name: "Lumparland",
    city: "438 Lumparland",
    stateCode: 21,
    state: "Åland",
  },
  {
    id: 478,
    name: "Mariehamn",
    city: "478 Mariehamn",
    stateCode: 21,
    state: "Åland",
  },
  {
    id: 736,
    name: "Saltvik",
    city: "736 Saltvik",
    stateCode: 21,
    state: "Åland",
  },
  {
    id: 766,
    name: "Sottunga",
    city: "766 Sottunga",
    stateCode: 21,
    state: "Åland",
  },
  {
    id: 771,
    name: "Sund",
    city: "771 Sund",
    stateCode: 21,
    state: "Åland",
  },
  {
    id: 941,
    name: "Vårdö",
    city: "941 Vårdö",
    stateCode: 21,
    state: "Åland",
  },
];

export const municipalities = municipalitiesUnsorted.sort(
  (a, b) => a.id - b.id
);
